version: "3.7"
services:
  web:
    image: nginx:alpine
    ports:
      - 10080:80
    volumes:
      - ./mywebdir:/data/www  
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/global:/etc/nginx/global
    depends_on:
      - php72
      - redis
      - db
  php72:
    image: dockertank/php72-fpm:tankv1
    ports:
      - 9000:9000
    volumes:
      - ./mywebdir:/data/www
  redis:
    image: redis
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sfkdb
      MYSQL_USER: sfkadmin
      MYSQL_PASSWORD: 123456
    volumes:
      - ./dbdata:/var/lib/mysql
